name: Build And Push

on:
  push:
    branches: ["main"]

jobs:

  security-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # For vulnerable dependencies
      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  build-and-push:
    needs: security-scans 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    env:
      GIT_SHA: ${{ github.sha }}
      USERNAME: ${{ vars.DOCKER_USERNAME }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' 
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with: 
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Build and Push Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          target: production
          tags: |
            ${{ vars.DOCKER_USERNAME }}/java:${{ github.sha }}
            ${{ vars.DOCKER_USERNAME }}/java:latest
          build-args: |
            GIT_SHA=${{ github.sha }}
            APP_VERSION=${{ vars.APP_VERSION }}
          sbom: true
          provenance: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # 5. Final Image Scanning
      - name: Docker Scout Scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ vars.DOCKER_USERNAME }}/java:${{ github.sha }}
          only-severities: critical,high
          exit-code: false 
