name: Pull And Deploy

on:
  workflow_run:
    workflows: ["Build And Push"]
    types: [completed]
  
jobs:

  pull-and-deploy:
    runs-on: self-hosted

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout only docker-compose.prod.yml
        uses: actions/checkout@v4
      
      - name: run the virtual environment
        run: |
          source venv/